name: cap_env
channels:
  - conda-forge
dependencies:
  - python=3.8

  # Main data handling
  - iris
  - xarray
  - pandas
  - geopandas

  # Plotting
  - hvplot
  - holoviews
  - geoviews
  - datashader
  - panel

  # Dev
  - pytest
  - flake8
